Simplify home_mode lookup so it works with keys that are variables
With the old code, and custom_users containing key "{{ mattermost_user }}",
ansible would barf:

TASK [users : home directory permissions] **************************************
task path: /home/jrodin/ansible-playbooks/tasks/users.yml:55
fatal: [mattermost-server-0.test]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'mattermost'\n\nThe error appears to have been in '/home/jrodin/ansible-playbooks/tasks/users.yml': line 55, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# https://docs.ansible.com/ansible/latest/modules/file_module.html\n- name:\n  ^ here\n"}

This is simpler anyway so we might as well just avoid this whole pitfall